dataset_root: "/media/david/emb"
batch_size: 12
learning_rate: 0.001
n_epochs: 1000
train_datasets: ['apparel']
test_datasets: ['objectnet']
num_workers: 4
project_name: GUIE
model_id: openCLIP+MLP
wandb_entity: celulaeucariota