dataset_root: "/mnt/colab_public/datasets/joan/gemb"
batch_size: 12
learning_rate: 0.001
n_epochs: 1000
train_datasets : ['apparel']
num_workers: 4
project_name: gemb_triplet_openCLIP
model_id: openCLIP+MLP
wandb_entity: joanrod